#!/usr/bin/env bash
# Protected Files Guard
# Blocks edits to sensitive files: secrets, lock files, minified assets, production configs.
# Exit 2 = block the tool call. Exit 0 = allow.

set -euo pipefail

TOOL_INPUT=$(cat)

# Extract file_path from JSON tool input
FILE_PATH=$(echo "$TOOL_INPUT" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1 2>/dev/null || true)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Resolve symlinks to prevent bypasses
FILE_PATH=$(readlink -f "$FILE_PATH" 2>/dev/null || echo "$FILE_PATH")

BASENAME=$(basename "$FILE_PATH")
LOWER_BASENAME=$(echo "$BASENAME" | tr '[:upper:]' '[:lower:]')

# --- Secrets / Environment files ---
case "$BASENAME" in
  .env|.env.*)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. Environment files contain secrets and should be edited manually."
    exit 2
    ;;
esac

# --- Lock files (auto-generated, should not be hand-edited) ---
case "$BASENAME" in
  package-lock.json|pnpm-lock.yaml|bun.lockb|yarn.lock|poetry.lock|go.sum|Gemfile.lock|composer.lock)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. Lock files are auto-generated by package managers."
    exit 2
    ;;
esac

# --- Minified files ---
case "$BASENAME" in
  *.min.js|*.min.css)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. Minified files are build artifacts."
    exit 2
    ;;
esac

# --- Production config ---
case "$BASENAME" in
  docker-compose.prod.yml|docker-compose.production.yml)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. Production configs should be changed through proper review."
    exit 2
    ;;
esac

# --- Secret / credential / key files ---
case "$LOWER_BASENAME" in
  *secret*|*credential*|*credentials*)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. File name suggests it contains secrets."
    exit 2
    ;;
esac

# PEM key files
case "$LOWER_BASENAME" in
  *key*.pem)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. PEM key files should not be modified by an agent."
    exit 2
    ;;
esac

# --- CI/CD workflow files ---
case "$FILE_PATH" in
  */.github/workflows/*.yml|*/.github/workflows/*.yaml)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. CI workflow configs should be changed through proper review."
    exit 2
    ;;
esac

# --- Terraform state files ---
case "$LOWER_BASENAME" in
  *.tfstate|*.tfstate.backup)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. Terraform state files contain secrets and should never be hand-edited."
    exit 2
    ;;
esac

# --- Files with sensitive keywords in name ---
case "$LOWER_BASENAME" in
  *token*|*auth*|*private*)
    echo "BLOCKED: Editing '$BASENAME' is not allowed. File name suggests it contains sensitive data."
    exit 2
    ;;
esac

# If none of the patterns matched, allow the edit
exit 0
