#!/usr/bin/env bash
# Session Logger
# Logs a summary of the Claude session to .claude/session-log.md when Claude stops responding.
# This hook runs on the Stop event.

set -uo pipefail

TOOL_INPUT=$(cat)

# Determine project root (look for .claude directory upward)
PROJECT_ROOT="$(pwd)"
SEARCH_DIR="$PROJECT_ROOT"
while [ "$SEARCH_DIR" != "/" ]; do
  if [ -d "$SEARCH_DIR/.claude" ]; then
    PROJECT_ROOT="$SEARCH_DIR"
    break
  fi
  SEARCH_DIR=$(dirname "$SEARCH_DIR")
done

LOG_DIR="$PROJECT_ROOT/.claude"
LOG_FILE="$LOG_DIR/session-log.md"

# Create log directory if it does not exist
mkdir -p "$LOG_DIR"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
DATE_HEADER=$(date '+%Y-%m-%d')

# Collect recently modified files (within the last 5 minutes)
CHANGED_FILES=""
if command -v find >/dev/null 2>&1; then
  CHANGED_FILES=$(find "$PROJECT_ROOT" \
    -not -path '*/.git/*' \
    -not -path '*/node_modules/*' \
    -not -path '*/.claude/*' \
    -not -path '*/dist/*' \
    -not -path '*/build/*' \
    -not -path '*/__pycache__/*' \
    -not -path '*/.next/*' \
    -type f \
    -newer "$LOG_DIR" \
    -mmin -5 \
    2>/dev/null | head -20 || true)
fi

# If no changed files detected, still log the session but note no changes
if [ -z "$CHANGED_FILES" ]; then
  # No file changes detected; skip logging to avoid noise
  exit 0
fi

# Count changed files
FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')

# Format the changed files as a markdown list (relative paths)
FILE_LIST=""
while IFS= read -r f; do
  if [ -n "$f" ]; then
    REL_PATH="${f#$PROJECT_ROOT/}"
    FILE_LIST="$FILE_LIST\n  - \`$REL_PATH\`"
  fi
done <<< "$CHANGED_FILES"

# Create or append to the log file
if [ ! -f "$LOG_FILE" ]; then
  {
    echo "# Claude Session Log"
    echo ""
    echo "Auto-generated by session-logger hook."
    echo ""
    echo "---"
    echo ""
  } > "$LOG_FILE"
fi

# Append session entry
{
  echo "## $DATE_HEADER"
  echo ""
  echo "### Session at $TIMESTAMP"
  echo ""
  echo "**Files changed ($FILE_COUNT):**"
  printf '%b\n' "$FILE_LIST"
  echo ""
  echo "---"
  echo ""
} >> "$LOG_FILE"

# Log rotation: if session-log.md exceeds 1000 lines, keep only the last 500
if [ -f "$LOG_FILE" ]; then
  LOG_LINES=$(wc -l < "$LOG_FILE" | tr -d ' ')
  if [ "$LOG_LINES" -gt 1000 ]; then
    tail -n 500 "$LOG_FILE" > "$LOG_FILE.tmp" && mv "$LOG_FILE.tmp" "$LOG_FILE"
  fi
fi

exit 0
